name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  decimal: ^3.2.1
  provider: ^6.1.2
  sqflite: ^2.4.1
  intl: ^0.20.1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/up.svg
    - assets/icons/down.svg
    - assets/icons/left.svg
    - assets/icons/right.svg
    - assets/icons/duo_down.svg
    - assets/icons/duo_up.svg
    - assets/icons/catering.svg
    - assets/icons/gouwu.svg
    - assets/icons/shezhi.svg
    - assets/icons/haizi.svg
    - assets/icons/shouji.svg
    - assets/icons/shuben.svg
    - assets/icons/huanqiuyinshi.svg
    - assets/icons/game.svg
    - assets/icons/bianzu2.svg
    - assets/icons/liwu.svg
    - assets/icons/yanjiu.svg
    - assets/icons/jiaren.svg
    - assets/icons/shipin.svg
    - assets/icons/jijiu.svg
    - assets/icons/jiaotong.svg
    - assets/icons/duo_down.svg
    - assets/icons/duo_up.svg

  fonts:
    - family: iconfonts
      fonts:
        - asset: assets/iconfonts/iconfonts.ttf